### ISSUE TITLE
how do i run this bot? i configured the config.yml but i dont know how to clone the repository or run it

### ISSUE THREAD

**Issue by Sak1nn** [ConnorSwis/casino-bot#53]
i dont really know python and i just want to have fun with a bot with my friends but it doesnt work

**Comment by Sak1nn** [comment]
when i try to run bot.py it shows this even though the token is correct


PS C:\Users\sbula\Downloads\casino-bot-main> & C:/Python312/python.exe c:/Users/sbula/Downloads/casino-bot-main/discord/bot.py
c:\Users\sbula\Downloads\casino-bot-main\discord\bot.py:16: RuntimeWarning: coroutine 'BotBase.load_extension' was never awaited
  client.load_extension(f'cogs.{filename[:-3]}')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2024-07-20 20:09:10 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\discord\http.py", line 803, in static_login
    data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\sbula\Downloads\casino-bot-main\discord\bot.py", line 18, in <module>
    client.run(TOKEN)
  File "C:\Python312\Lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\discord\client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Python312\Lib\site-packages\discord\client.py", line 777, in start
    await self.login(token)
  File "C:\Python312\Lib\site-packages\discord\client.py", line 612, in login
    data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\discord\http.py", line 807, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
PS C:\Users\sbula\Downloads\casino-bot-main>

**Comment by plawandos** [comment]
https://github.com/plawandos/HOUSE-2

you can use my version which fixes a lot of things. that saying his code works well you just need python 3.7.0 and the exact version of the modules listed in requirement.txt

**Comment by ConnorSwis** [comment]
Thanks for your interest in my casino bot. I hope that since July of last year, you have learned to read your error traceback, but in case you haven't, at the bottom of the error message, it says `discord.errors.LoginFailure: Improper token has been passed.` which means an improper token has been passed.

**Comment by ConnorSwis** [comment]
Also the code is broken because you are using the wrong version of python which means your packages are different versions than the ones specified in [requirements.txt](https://github.com/ConnorSwis/casino-bot/blob/main/requirements.txt).
